# Generated by Django 2.0.6 on 2018-06-05 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_code', models.IntegerField(verbose_name='Course Code')),
                ('c_name', models.CharField(max_length=200, verbose_name='Course Name')),
                ('c_seats', models.IntegerField(verbose_name='Number of Seats')),
                ('c_desc', models.TextField(blank=True, verbose_name='Course Description')),
            ],
            options={
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('s_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Student ID')),
                ('s_first_name', models.CharField(max_length=200, verbose_name='First Name')),
                ('s_last_name', models.CharField(max_length=200, verbose_name='Last Name')),
                ('s_pic', models.ImageField(blank=True, upload_to='student_pics', verbose_name="Student's pic")),
                ('course', models.ManyToManyField(blank=True, to='students.Course', verbose_name='Courses')),
            ],
            options={
                'db_table': 'students',
                'ordering': ['s_id'],
            },
        ),
        migrations.AlterField(
            model_name='department',
            name='d_chair',
            field=models.CharField(max_length=200, verbose_name='Department Chair'),
        ),
        migrations.AlterField(
            model_name='department',
            name='d_code',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Department Code'),
        ),
        migrations.AlterField(
            model_name='department',
            name='d_name',
            field=models.CharField(max_length=200, verbose_name='Department Name'),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Department', verbose_name='Department Code'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('department', 'c_code')},
        ),
    ]
